import { useState } from "react";

export default function SummarizeButton({
  textToSummarize,
}: {
  textToSummarize: string;
}) {
  const [isSummarizing, setIsSummarizing] = useState(false);
  const [summarizedText, setSummarizedText] = useState<string>("");
  const current_env = import.meta.env.PUBLIC_CURRENT_ENV;
  const endpointPrefix =
    current_env == "DEV"
      ? "http://localhost:4321"
      : "https://datajournal.datakyu.co";

  async function handleSummarization({ text }: { text: string }) {
    const prompt = `
    Summarize the blog post below as ONE coherent paragraph of plain text (no headings, bullets, bold, emojis, quotes, or preamble). Hard limit: 110 words. Use 3–5 sentences in neutral, active voice. Include only: what the post is about, the core claim/question, the 2–3 most important points or findings, and the net takeaway for the reader. Preserve essential names, products, and any critical numbers; drop anecdotes, minor examples, and marketing fluff. If it's a comparison, state which option is favored and why in one short clause. Do not add opinions or assumptions, do not repeat the title, and do not exceed the word limit—omit less important points instead. Here is the content: ${text}`;
    try {
      setIsSummarizing(true);
      const response = await fetch(`${endpointPrefix}/api/openai/`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt: prompt }),
      });

      if (!response.ok) {
        const errorPayload = await response.json();
        throw new Error(
          `HTTP error! Status: ${response.status}. Error: ${errorPayload.error}`,
        );
      }

      const data = await response.json();
      setSummarizedText(data.text);
      setIsSummarizing(false);
    } catch (error) {
      console.error("Error fetching translation:", error);
      setSummarizedText("Summarization failed. Please try again.");
    }
  }

  function handleTrackingClick() {
    if (!window.analytics) {
      console.error("Segment not detected.");
      return;
    }
    window.analytics.track("Used Summarization", {
      article_title:
        document.querySelector("h1")?.textContent || "Unknown title",
    });
  }

  return (
    <div>
      <button
        className={`inline-flex items-center gap-2 px-5 py-2.5 bg-zinc-900 text-white text-sm font-manrope font-semibold rounded-full transition-all duration-200 hover:bg-[#E8522A] ${isSummarizing ? "opacity-40 cursor-not-allowed" : "hover:scale-[1.02]"}`}
        disabled={isSummarizing}
        onClick={() => {
          handleSummarization({ text: textToSummarize });
          handleTrackingClick();
        }}
      >
        <svg
          width="14"
          height="14"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2.5"
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          <path d="M12 3l1.5 4.5L18 9l-4.5 1.5L12 15l-1.5-4.5L6 9l4.5-1.5z" />
        </svg>
        {isSummarizing ? "Summarizing..." : "Summarize with AI"}
      </button>
      {summarizedText && (
        <div
          className="p-6 bg-linear-to-br`(suggestCanonicalClasses) from-purple-50 via-blue-50 to-cyan-50 rounded-2xl shadow-lg border border-purple-100/50 
     text-lg leading-relaxed text-gray-800"
        >
          <div className="flex items-center gap-2 mb-3 text-sm text-purple-600 font-medium">
            <div className="text-sm text-gray-500 mb-2">✨ Generated by AI</div>
          </div>
          {summarizedText}
        </div>
      )}
    </div>
  );
}
