import { useState } from "react";

export default function SummarizeButton({
  textToSummarize,
}: {
  textToSummarize: string;
}) {
  const [isSummarizing, setIsSummarizing] = useState(false);
  const [summarizedText, setSummarizedText] = useState<string>("");
  const current_env = import.meta.env.PUBLIC_CURRENT_ENV;
  const endpointPrefix =
    current_env == "DEV"
      ? "http://localhost:4321"
      : "https://datajournal.datakyu.co";

  async function handleSummarization({ text }: { text: string }) {
    const prompt = `
    Summarize the blog post below as ONE coherent paragraph of plain text (no headings, bullets, bold, emojis, quotes, or preamble). Hard limit: 110 words. Use 3–5 sentences in neutral, active voice. Include only: what the post is about, the core claim/question, the 2–3 most important points or findings, and the net takeaway for the reader. Preserve essential names, products, and any critical numbers; drop anecdotes, minor examples, and marketing fluff. If it's a comparison, state which option is favored and why in one short clause. Do not add opinions or assumptions, do not repeat the title, and do not exceed the word limit—omit less important points instead. Here is the content: ${text}`;
    try {
      setIsSummarizing(true);
      const response = await fetch(`${endpointPrefix}/api/openai/`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt: prompt }),
      });

      if (!response.ok) {
        const errorPayload = await response.json();
        throw new Error(
          `HTTP error! Status: ${response.status}. Error: ${errorPayload.error}`,
        );
      }

      const data = await response.json();
      setSummarizedText(data.text);
      setIsSummarizing(false);
    } catch (error) {
      console.error("Error fetching translation:", error);
      setSummarizedText("Summarization failed. Please try again.");
    }
  }

  return (
    <div>
      <button
        className={`inline-flex items-center px-5 py-2 rounded-full font-medium text-white shadow-md border-2 border-transparent my-4 bg-[linear-gradient(90deg,#6366f1_0%,#8b5cf6_30%,#06b6d4_100%)] ${isSummarizing ? "opacity-50 cursor-not-allowed" : ""}`}
        onClick={() => handleSummarization({ text: textToSummarize })}
      >
        {isSummarizing ? "Summarizing..." : "Summarize with AI"}
      </button>
      {summarizedText && (
        <div
          className="p-6 bg-gradient-to-br from-purple-50 via-blue-50 to-cyan-50 rounded-2xl shadow-lg border border-purple-100/50 
     text-lg leading-relaxed text-gray-800"
        >
          <div className="flex items-center gap-2 mb-3 text-sm text-purple-600 font-medium">
            <div className="text-sm text-gray-500 mb-2">✨ Generated by AI</div>
          </div>
          {summarizedText}
        </div>
      )}
    </div>
  );
}
